### PR TITLE
add mindist maxdist options, use uniform

### PR DESCRIPTION
**Pull request by dinhhuy2109**

### CODE REVIEW

**Comment by fsuarez6** [comment]
Set the default value of `mindist=0` so that existing code doesn't break

**Comment by dinhhuy2109** [comment]
It will still break. Because existing codes are using this 
`criros.exploration.random_point_inside_fov(camera_info, maxdist=maxdist, Tcamera=Tcamera)`

**Comment by fsuarez6** [comment]
If you define the function like this:
```python
def random_point_inside_fov(camera_info, maxdist, mindist=0, Tcamera=np.eye(4)):
```
Does it break?

**Comment by dinhhuy2109** [comment]
I just pushed

**Pull request merged**
